### ISSUE TITLE
Not able to pull zones from Tech M-9r 1.3.8

### ISSUE THREAD

**Issue by vanwegen** [tomaszkoperski/com.tech-controllers#3]
Hi, Just installed the app, but unfortunately it does not seem to work with my controller.
This is a M-9r connected to 3 EU-L-9 R's with in total 13 zones of floor heating.

There seems to be little options for troubleshooting. Hope that you can help me out, as it is a fundamental part in smartening my home :)

**Comment by tomaszkoperski** [comment]
Hi. What exactly happens - were you able to add the devices? Please try reaching the point in which you see the failure, go to app details screen and submit a diagnostics report, then post the ID of the report here - I'll have a look. Cheers!

**Comment by vanwegen** [comment]
Hi, so weird. It now seems to work fine. Didn't change a thing. 
However: I did add the controller in HomeAssistant, just to check if I could get it to work there (which worked fine straight away). Anyway, I'll come back when I can report something
