### ISSUE TITLE
Null on elements list

### ISSUE THREAD

**Issue by chobart** [tomaszkoperski/com.tech-controllers#6]
First of all, thank you for the app!

 <img width="803" alt="Zrzut ekranu 2024-10-18 o 12 07 38" src="https://github.com/user-attachments/assets/b97e7c37-aded-4e15-b28b-f70a61a8a5f7">

My elements list contains null. This causes an error when accessing `zone.zone`. I tried to add a pull request, but I don't have permission to push a branch.  This small change fixes that:
```
-          if (zone.zone.zoneState !== "zoneOff" && true) {
+          if (zone && zone.zone.zoneState !== "zoneOff") {
```

**Comment by tomaszkoperski** [comment]
Thanks for reporting the problem. I've fixed that and will publish new version to Homey shortly.

**Comment by tomaszkoperski** [comment]
Changed in v1.0.3
